# ********RoostGPT********
"""
Test generated by RoostGPT for test aman28thMay using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=addition_9ccff787e3
ROOST_METHOD_SIG_HASH=addition_77ffd3333b

Scenario 1: Verify the addition of two positive numbers
Details:
  TestName: test_addition_positive_numbers
  Description: This test is intended to verify the addition of two positive numbers. This is a straightforward test to check the basic functionality of the addition function.
Execution:
  Arrange: Initialize two positive numbers, num1 and num2.
  Act: Invoke the addition function with num1 and num2 as parameters.
  Assert: Check if the returned result is the sum of num1 and num2.
Validation:
  This test is important as it checks the basic functionality of the addition function. The function is expected to correctly add two positive numbers.

Scenario 2: Verify the addition of positive and negative numbers
Details:
  TestName: test_addition_positive_negative_numbers
  Description: This test is intended to verify the addition of a positive number and a negative number.
Execution:
  Arrange: Initialize a positive number and a negative number, num1 and num2 respectively.
  Act: Invoke the addition function with num1 and num2 as parameters.
  Assert: Check if the returned result is the sum of num1 and num2.
Validation:
  This test is important as it checks the function's ability to handle both positive and negative numbers. The function is expected to correctly add a positive number and a negative number.

Scenario 3: Verify the addition of two negative numbers
Details:
  TestName: test_addition_negative_numbers
  Description: This test is intended to verify the addition of two negative numbers.
Execution:
  Arrange: Initialize two negative numbers, num1 and num2.
  Act: Invoke the addition function with num1 and num2 as parameters.
  Assert: Check if the returned result is the sum of num1 and num2.
Validation:
  This test is important as it checks the function's ability to handle negative numbers. The function is expected to correctly add two negative numbers.

Scenario 4: Verify the addition of two zero numbers
Details:
  TestName: test_addition_zero_numbers
  Description: This test is intended to verify the addition of two zero numbers.
Execution:
  Arrange: Initialize two zero numbers, num1 and num2.
  Act: Invoke the addition function with num1 and num2 as parameters.
  Assert: Check if the returned result is zero.
Validation:
  This test is important as it checks the function's ability to handle zero numbers. The function is expected to correctly add two zero numbers and return zero.

Scenario 5: Verify the addition of a number and zero
Details:
  TestName: test_addition_number_zero
  Description: This test is intended to verify the addition of a non-zero number and zero.
Execution:
  Arrange: Initialize a non-zero number and zero, num1 and num2 respectively.
  Act: Invoke the addition function with num1 and num2 as parameters.
  Assert: Check if the returned result is equal to the non-zero number.
Validation:
  This test is important as it checks the function's ability to handle the addition of a number and zero. The function is expected to correctly return the non-zero number when added with zero.
"""

# ********RoostGPT********
import pytest
from calc import addition

class Test_CalcAddition:

    def test_addition_positive_numbers(self):
        # Arrange
        num1 = 10
        num2 = 5
        expected_result = 15

        # Act
        result = addition(num1, num2)

        # Assert
        assert result == expected_result, f'Expected {expected_result}, but got {result}'

    def test_addition_positive_negative_numbers(self):
        # Arrange
        num1 = 10
        num2 = -5
        expected_result = 5

        # Act
        result = addition(num1, num2)

        # Assert
        assert result == expected_result, f'Expected {expected_result}, but got {result}'

    def test_addition_negative_numbers(self):
        # Arrange
        num1 = -10
        num2 = -5
        expected_result = -15

        # Act
        result = addition(num1, num2)

        # Assert
        assert result == expected_result, f'Expected {expected_result}, but got {result}'

    def test_addition_zero_numbers(self):
        # Arrange
        num1 = 0
        num2 = 0
        expected_result = 0

        # Act
        result = addition(num1, num2)

        # Assert
        assert result == expected_result, f'Expected {expected_result}, but got {result}'

    def test_addition_number_zero(self):
        # Arrange
        num1 = 10
        num2 = 0
        expected_result = 10

        # Act
        result = addition(num1, num2)

        # Assert
        assert result == expected_result, f'Expected {expected_result}, but got {result}'
